version: '3.8'

volumes:
  mysql-data-web24:
    driver: local

services:
  web24:
    container_name: web24
    build:
      context: ./
      dockerfile: Dockerfile
    extra_hosts:
      host.docker.internal: host-gateway
    ports:
      - "81:80"
    volumes:
      - ./service-company:/var/www/html
    depends_on:
      web24-db:
        condition: service_healthy

  web24-db:
    container_name: web24-db
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: web24
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql-data-web24:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10


  phpmyadmin-web24:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-web24
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: web24-db
